### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by sargunv** [sultanskyman/WildSex#8]
Getting a NPE on Spigot for MC 1.10

```
[19:28:28] [Server thread/WARN]: [WildSex] Task #3 for WildSex v3.6 generated an exception
java.lang.NullPointerException
at net.minecraft.server.v1_10_R1.EntityAnimal.c(EntityAnimal.java:128) ~[mcserver.jar:git-Spigot-850da7e-251a5b6]
at com.cemgokmen.wildsex.wildanimal.v1_10_R1.WildAnimalHandler.startLoveMode(WildAnimalHandler.java:28) ~[?:?]
at com.cemgokmen.wildsex.WildSexTask.run(WildSexTask.java:56) ~[?:?]
at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[mcserver.jar:git-Spigot-850da7e-251a5b6]
at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [mcserver.jar:git-Spigot-850da7e-251a5b6]
at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [mcserver.jar:git-Spigot-850da7e-251a5b6]
at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [mcserver.jar:git-Spigot-850da7e-251a5b6]
at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [mcserver.jar:git-Spigot-850da7e-251a5b6]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [mcserver.jar:git-Spigot-850da7e-251a5b6]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_101]
```

**Comment by DrkMatr1984** [comment]
I'll see what I can do. I've lost interest in MC for the time being but am still trying to maintain my plugins. I'll try to fix this soon.

**Comment by sargunv** [comment]
No rush, I've written my own plugin to replicate this one.

**Comment by cgokmen** [comment]
I've also been away from the scene for a while but I may be returning soon.

I did look at your plugin and I saw your autobreed module, however the primary advantage of this plugin over that one is multi-version compatibility (yours is set up to support one version at a time due to the use of the CraftAgeable interface) and imagine that may become an issue in the future.

However, seeing how for the time being the issue here rests unsolved, I am posting the link to your plugin here, in case someone reads this desperately needing this plugin to work for them:
https://github.com/sargunster/bukkit-smart-farm

We will however try to fix the issue as soon as possible.

**Comment by cgokmen** [comment]
@sargunster , the update supporting MC 1.10.2 and 1.11 is now ready as WildSex 4, you can get it in the releases tab. It is also awaiting BukkitDev approval.

@DrkMatr1984 , I have broken backwards compatibility in the new version and gotten rid of the BKCommonLib dependency. I have also rewritten the 1.10.2 and 1.11 wildanimalhandler implementation using Reflection because it's not possible to use the method we previously used (because when you pass a null human to it, it tries to access his inventory without checking if not null first). So I would appreciate it if you could pull this into your fork (and for future updates, please merge back into this repo so that we have the latest version here!)

Anyway, resolved.

**Comment by DrkMatr1984** [comment]
I just completely deleted my old fork and reforked your repo. Users can get earlier versions via bukkit and your old PRs if they'd like. I'll merge all future updates with the new version following the new format.
